blog_init/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.init, name='init'),
    path('myBG/', views.topics, name='topics'),
    path('topicos/', views.topicos, name='topicos'),
    path('adicionar_topico/', views.adicionarTopico, name='adicionarTopico'),
    path('apagarTopico/<int:topico_id>/', views.apagarTopico, name='apagarTopico'),
    path('assuntos/<int:topico_id>/', views.assuntos, name='assuntos'),
    path('assuntos2/', views.assuntos2, name='assuntos2'),
    path('anotações/<int:topico_id>', views.novaEntrada, name='novaEntrada'),
    path('upload_to_assunto/<int:topico_id>', views.upload_to_assunto, name='upload_to_assunto'),
    path('conteudo/<int:entrada_id>/', views.conteudo, name='conteudo'),
    path('pagarentrada/<int:entrada_id>/', views.apagarEntrada, name='apagarEntrada'),
    path('editar/<int:entrada_id>/', views.atualizarEntrada, name='atualizarEntrada'),
    path('perfil/', views.perfil, name='perfil'),
    path('perfilfoto/', views.uploadImage, name='uploadImage'),
    path('blogMy/', views.blogall, name='blogall'),
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("Blogme/", include('blog_init.urls')),
    path("users/", include('users.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    path('login/', views.login, name='login'),
    path('cadastro/', views.registrar, name='registrar'),
    path('logout/', views.logout_views, name='logout')
]

blog_init/models.py
from django.db import models
from django.contrib.auth.models import User


class Topicos(models.Model):
    """ Responsável por cadastrar os tópicos """
    text = models.CharField(max_length=200)
    data_add = models.DateTimeField(auto_now_add=True)
    
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        """Devolve uma apresentação em string para o banco de dados"""
        return self.text
    
class Entrada(models.Model):
    """Responsável por cadastrar os textos dentro de cada topico"""
    topic = models.ForeignKey(Topicos, on_delete=models.CASCADE)
    text = models.TextField()
    imagem = models.ImageField(upload_to='upload_to_assunto', null=True, blank=True)
    data_add = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.text[:50]

class Perfil(models.Model):
    """Responsável pela foto do usuário"""
    foto = models.ImageField(upload_to='perfil_foto', blank=True, null=True)
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"Foto do usuário {self.usuario.username}"

blog_init/forms.py
from django import forms
from .models import Topicos, Entrada, Perfil

    
class NovoTopico(forms.ModelForm):
    class Meta:
        model = Topicos
        fields = ['text']
        labels = {'text': ''}

class NovaEntrada(forms.ModelForm):
    class Meta:
        model = Entrada
        fields = ['text', 'imagem']
        labels = {'text': 'Escreva o assunto', 'imagem': 'Upload de imagem (não obrigatório)'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

class FotoForm(forms.ModelForm):
    class Meta:
        model = Perfil
        fields = ['foto']
        labels = {'foto': 'Upload de imagem (não obrigatório)'}
        

blog_init/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, Http404
from .forms import  NovaEntrada, NovoTopico, FotoForm
from .models import Topicos, Entrada, Perfil
from django.urls import reverse

# Create your views here.

def init(request):
    # Pagina iicial
    return render(request, 'index.html')

@login_required
def topics(request):
    return render(request, 'blog.html')

@login_required
def topicos(request):
    """ Lista todos os topicos """
    topicos = Topicos.objects.filter(owner=request.user).order_by('data_add')
    contexto = {'topicos': topicos}
    return render(request, 'topicos.html', contexto)

@login_required
def adicionarTopico(request):
    """ Registra novos tópicos"""
    if request.method != 'POST':
        form = NovoTopico()
    else:
        form = NovoTopico(request.POST)
        if form.is_valid():
            novo_topico = form.save(commit=False)
            novo_topico.owner = request.user
            novo_topico.save()
            return HttpResponseRedirect(reverse(topicos))
    contexto = {'form': form}
    return render(request, 'novotopico.html', contexto)


@login_required
def apagarTopico(request, topico_id):
    apagar = get_object_or_404(Topicos, id=topico_id)
    
    if request.method == 'POST':
        apagar.delete()
        return redirect('topicos')
    return render(request, 'topicos.html', {'apagar':apagar})

@login_required
def apagarEntrada(request, entrada_id):
    apagar = get_object_or_404(Entrada, id=entrada_id)
    topic_id = apagar.topic.id
    if request.method == 'POST':
        apagar.delete()
        return redirect('assuntos', topico_id=topic_id)
    return render(request, 'assuntos.html', {'apagar':apagar})

@login_required
def novaEntrada(request, topico_id):
    topico = Topicos.objects.get(id=topico_id)
    
    if topico.owner != request.user:
        raise Http404
    
    if request.method != 'POST':
        form = NovaEntrada()
    else:
        form = NovaEntrada(data=request.POST, files=request.FILES)
        if form.is_valid():
            nova_entrada = form.save(commit=False)
            nova_entrada.topic = topico 
            nova_entrada.save()
            return redirect(reverse('assuntos', args=[topico_id]))
    
    contexto = {'form': form, 'topico': topico}
    return render(request, 'novaentrada.html', contexto)

@login_required    
def assuntos(request, topico_id):
    topico = Topicos.objects.get(id=topico_id)
    
    if topico.owner != request.user:
        raise Http404
    
    entradas = topico.entrada_set.order_by('-data_add')
    contexto = {'topico':topico, 'entradas': entradas}
    return render(request, 'assuntos.html', contexto)

def assuntos2(request):
    topicos = Topicos.objects.filter(owner=request.user).order_by('data_add')
    contexto = {'topicos': topicos}
    return render(request, 'assuntos2.html', contexto)
    
@login_required
def upload_to_assunto(instance, filename):
    return f'assuntos/{instance.topic.id}/{filename}'


@login_required
def conteudo(request, entrada_id):
    entrada = get_object_or_404(Entrada, id=entrada_id)
    topic = entrada.topic
    
    
        # Requisição inicial, preenche previamente o formulárrio com a enrada atual
    form = NovaEntrada(instance=entrada)
        
    
    contexto = {'entrada':entrada, 'topico':topic, 'form': form}
    return render(request, 'conteudo.html', contexto)

@login_required
def atualizarEntrada(request, entrada_id):
    entrada = Entrada.objects.get(id=entrada_id)
    topic = entrada.topic
    
    if topic.owner != request.user:
        raise Http404
    
    
    if request.method == 'POST':
        form = NovaEntrada(instance=entrada, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('assuntos', args=[topic.id]))
    else:
        form = NovaEntrada(instance=entrada)
        
    context = {'entrada':entrada, 'form':form, 'topic':topic}
    return render(request, 'editartexto.html', context)


@login_required
def perfil(request):
    return render(request, 'perfil.html')

@login_required
def uploadImage(request):

    perfil, created = Perfil.objects.get_or_create(usuario=request.user)

    if request.method == 'POST':
        form = FotoForm(request.POST, request.FILES, instance=perfil)
        if form.is_valid():
            form.save()  
            return redirect(reverse('perfil'))
    else:
        form = FotoForm(instance=perfil)  # Exibir o formulário com a foto existente, se houver
    
    contexto = {'form': form}
    return render(request, 'perfilfoto.html', contexto)

@login_required
def blogall(request):
    entradas = Entrada.objects.all() 
    return render(request, 'blog2.html', {'entradas': entradas})

blog_init/templates/assuntos.html
{% extends 'baseblog.html' %}
{% load static %}

{% block link %}
 <link rel="stylesheet" href="{% static 'perfil/css/assuntos.css' %}">
 <link rel="stylesheet" href="{% static 'perfil/css/cores.css' %}">
{% endblock %}
 
{% block main %}
  <div class="container">
    <div class="titulo">
      <p>Tópico: {{topico}}</p>
      <a href="{% url 'novaEntrada' topico.id %}">Novo conteúdo</a>
    </div>
    <br>
    <br>
    <div class="container2">
      {% for entrada in entradas %}
      <ul class="cart">
        <p class="data">{{ entrada.data_add | date:'M d, Y H:i'}}</p>
        {% if entrada.imagem %}
          <img src="{{ entrada.imagem.url }}" alt="Imagem do assunto">
        {% endif %}
        <p class="texto">
          <span class="text-content">{{ entrada.text|slice:":20" }}</span>
          {% if entrada.text|length > 20 %}
            <span class="text-more">... <a href="{% url  'conteudo' entrada.id %}" class="text-toggle">Mostrar mais</a></span>
            <span class="text-full" style="display:none;">{{ entrada.text }}</span>
          {% endif %}
        </p>
        <div class="btn">
          <form action="{% url 'apagarEntrada' entrada.id %} " method="post">
            {% csrf_token %}
            <button name="submit" class="apagar">Excluir</button>
          </form>
          <form  action="{% url 'atualizarEntrada' entrada.id %} " method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <button name="submit" class="apagar">Editar</button>
          </form>
        </div>
      </ul>
    {% empty %}  
      <p class="nregister">Não há registro</p>
    {% endfor %}
    </div>
  </div>  
{% endblock %}
{% block script %}
  <script src="{% static 'perfil/js/mais.js' %}"></script>
{% endblock%}

blog_init/templates/assuntos2.html
{% extends 'baseblog.html' %}
{% load static %}

{% block link %}
 <link rel="stylesheet" href="{% static 'perfil/css/assuntos2.css' %}">
 <link rel="stylesheet" href="{% static 'perfil/css/cores.css' %}">
{% endblock %}

{% block main %}

<div class="titulo">
    <h2> Escolha o tópico que deseja escrever sobre! </h2>
    <p> Clique em cima e ele te rendicionará para a pagina de edição. </p>
</div>

<div class="topicos">
  {% if topicos %}
    <div class="topicos_cart">
        {% for topico in topicos %}

          <p>
            <a href="{% url 'assuntos' topico.id %}">{{ topico }}</a>
          </p>
    
        {% endfor %}
    </div>
  {% endif %}
</div>
{% endblock %}

blog_init/templates/blog.html
{% extends 'baseblog.html'%}
{% load static %}
{% block link%}
 <link rel="stylesheet" href="{% static 'perfil/css/blog.css' %}">
 <link rel="stylesheet" href="{% static 'perfil/css/cores.css' %}">
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css" />
{% endblock %}

{% block main %}

    <div class="container_1">
        <h2>Bem Vindo(a)! {{user.username}}</h2>
        <h4>Comece já sua primeira publicação!!!</h4>
    </div>
    <div class="container2">
        <div class="passos" id="a" data-aos="fade-up" data-aos-duration="1500" data-aos-delay="300">
            <h5>Primeiro passo</h5>
            <p>Entre em tópicos e adicione quandos quiser, eles serão suas categorias.</p>
        </div>
        <div class="passos" id="b" data-aos="fade-up" data-aos-duration="1500" data-aos-delay="300">
            <h5>Segundo passo</h5>
            <p>Entre em Assuntos e escolha um tópico já criado, coloque quantos assuntos, artigos e curiosidades que quiser dentro de cada um!</p>
        </div>
        <div class="passos" id="c" data-aos="fade-up" data-aos-duration="1500" data-aos-delay="300">
            <h5>Terceiro passo</h5>
            <p>Entre em Perfil e anexe sua foto, lá será a capa do seu perfil.</p>
        </div>
        <div class="passos" id="d" data-aos="fade-up" data-aos-duration="1500" data-aos-delay="300">
            <h5>Quinto passo</h5>
            <p>Entre em Blog e aptoveite! lá terá todas suas publicações, das mais novas á mais antigas</p>
        </div>
    </div>
{% endblock %}

{% block script %}
 <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js"></script>
   <script>
     AOS.init(); // Inicializa o AOS
   </script>
{% endblock %}

blog_init/templates/blog2.html
{% extends 'baseblog.html' %}
{% load static %}

{% block link %}
 <link rel="stylesheet" href="{% static 'perfil/css/assuntos.css' %}">
 <link rel="stylesheet" href="{% static 'perfil/css/cores.css' %}">
{% endblock %}

{% block main %}
  <div class="container">
    <div class="titulo">
      <p>Todos os Assuntos</p>
    </div>
    <br>
    <br>
    <div class="container2">
      {% for entrada in entradas %}
      <ul class="cart">
        <p class="data">{{ entrada.data_add | date:'M d, Y H:i'}}</p>
        {% if entrada.imagem %}
          <img src="{{ entrada.imagem.url }}" alt="Imagem do assunto">
        {% endif %}
        <p class="texto">
          <span class="text-content">{{ entrada.text|slice:":20" }}</span>
          {% if entrada.text|length > 20 %}
            <span class="text-more">... <a href="{% url  'conteudo' entrada.id %}" class="text-toggle">Mostrar mais</a></span>
            <span class="text-full" style="display:none;">{{ entrada.text }}</span>
          {% endif %}
        </p>
      </ul>
    {% empty %}  
      <p class="nregister">Não há registro</p>
    {% endfor %}
    </div>
  </div>  
{% endblock %}

blog_init/templates/conteudo.html
{% extends 'baseblog.html' %}

{% load static %}

{% block link %}
 <link rel="stylesheet" href="{% static 'perfil/css/conteudo.css' %}">
 <link rel="stylesheet" href="{% static 'perfil/css/cores.css' %}">
{% endblock %}

{% block main %}
<div class="conatiner">
  
    <p class="data">{{ entrada.data_add | date:'M d, Y H:i'}}</p>
    {% if entrada.imagem %}
      <img src="{{ entrada.imagem.url }}" alt="Imagem do assunto">
    {% endif %}
    <p>{{ entrada.text }}</p>
    <br>
    <div class="btn">
      <a href="{% url 'blogall' %}">Voltar</a>
    </div>
</div>
{% endblock %}

blog_init/templates/editartexto.html
{% extends 'baseblog.html' %}
{% load static %}

{% block link %}
   <link rel="stylesheet" href="{% static 'perfil/css/newentry.css'%}">
   <link rel="stylesheet" href="{% static 'perfil/css/cores.css'%}">
{% endblock %}


{% block main %}
    <div class="container">
        <form action="{% url 'atualizarEntrada' entrada.id %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
                <!-- Campo de texto -->
            <div class="form-group">
                {{ form.text.label_tag }}
                {{ form.text }}
            </div>
    
                <!-- Campo de imagem customizado -->
                <div class="form-group">
                <label for="id_imagem" class="custom-upload">
                    <span>Escolher Imagem</span>
                </label>
                {{ form.imagem }}
                <img id="preview" src="#" alt="Pré-visualização" style="display: none; max-width: 100px;">
                </div>
    
                <!-- Botão de publicar -->
                <button type="submit" class="btn btn-primary">Publicar</button>
         
        </form>
        
    </div>
{% endblock%}

{% block script %}
   <script>
      document.getElementById('id_imagem').addEventListener('change', function(event) {
         const reader = new FileReader();
         reader.onload = function() {
            const preview = document.getElementById('preview');
            preview.src = reader.result;
            preview.style.display = 'block';
         };
         reader.readAsDataURL(event.target.files[0]);
      });
   </script>
{% endblock %}

blog_init/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block link %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css" />
  <link rel="stylesheet" href="{% static 'general/css/home.css' %}">
{% endblock %}

{% block main %}
  <!-- Container com conteúdo home -->
  <div class="container_head">
    <div id="particles-js"></div>
    <div class="titulo">
      <h2>Conheça nosso BlogMY</h2>
      <p>Compartilhando ideias e momentos que moldam nossa jornada, um post de cada vez.</p>
    </div>
  </div>

  <!-- Container com conteúdo Sobre -->
  <div class="container_sobre" id="section1">
    <br>
    <br>
    <div class="sobre" id="sob-public"  data-aos="fade-up" data-aos-duration="1500" data-aos-delay="300">
        <h3>Publicação de posts</h3>
        <p>Acompanhe novos artigos e conteúdos, com textos, imagens e vídeos organizados por categorias e tags para facilitar sua leitura.</p>
    </div>
    <div class="sobre" id="sob-comen" data-aos="fade-up" data-aos-duration="1500" data-aos-delay="300">
        <h3>Comentários</h3>
        <p>Participe da conversa! Deixe suas opiniões e interaja com outros leitores nos comentários de cada post.</p>
    </div>
    <div class="sobre" id="sob-pesquisa" data-aos="fade-up" data-aos-duration="1500" data-aos-delay="300">
        <h3>Pesquisa e categorias</h3>
        <p> Encontre facilmente o que procura usando nossa ferramenta de busca ou navegando por categorias e tags.</p>
    </div>
    <div class="sobre" id="sob-assi" data-aos="fade-up" data-aos-duration="1500" data-aos-delay="300">
        <h3>Assinatura de novidades</h3>
        <p>Não perca nada! Inscreva-se para receber notificações ou e-mails sempre que um novo post for publicado.</p>
    </div>
  </div>

  <!-- container vale comigo-->
  <div class="container_contato" id="section2">
    <div class="gostou">
        <h3>Alguma duvida? entre em contato comigo!</h3>
        <h5>Kethelyn Cavalari</h5>
    </div>
    <div class="contatos">
        <ul>
            <li><a href="https://github.com/Kethelynl" class="icon"><img src="{% static 'general/img/github.png'%}" ></a></li>
            <li><a href="https://www.linkedin.com/in/kethelyn-cavalari/" class="icon"><img src="{% static 'general/img/linkedin.png'%}" alt=""></a></li>
            <li><a href="https://wa.me/5511984870198?text=Olá%2C%20gostei%20do%20seu%20perfil%20podemos%20conversar?" target="_blank" class="icon"><img src="{% static 'general/img/whatss.png'%}" alt=""></a></li>
            <li><a href="mailto:kethcavalari@gmail.com" class="icon"><img src="{% static 'general/img/email.png'%}" alt=""></a></li>
        </ul>
    </div>
  </div>
{% endblock %}

{% block script %}
   <script src="https://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script>
   <script>
    particlesJS("particles-js", {
        "particles": {
            "number": {
                "value": 100
            },
            "color": {
                "value": "#ffffff"
            },
            "shape": {
                "type": ""
            },
            "opacity": {
                "value": 0.5
            },
            "size": {
                "value": 5
            },
            "line_linked": {
                "enable": true,
                "distance": 150,
                "color": "#ffffff",
                "opacity": 0.4,
                "width": 1
            },
            "move": {
                "enable": true,
                "speed": 2
            }
        }
     });
   </script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js"></script>
   <script>
     AOS.init(); // Inicializa o AOS
   </script>
{% endblock %}

blog_init/templates/novaentrada.html
{% extends 'baseblog.html' %}
{% load static %}

{% block link %}
   <link rel="stylesheet" href="{% static 'perfil/css/newentry.css'%}">
   <link rel="stylesheet" href="{% static 'perfil/css/cores.css'%}">
{% endblock %}

{% block main %} 
   <div class="container">
      <form action="{% url 'novaEntrada' topico.id %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- Campo de texto -->
        <div class="form-group">
         {{ form.text.label_tag }}
         {{ form.text }}
        </div>

         <!-- Campo de imagem customizado -->
         <div class="form-group">
            <label for="id_imagem" class="custom-upload">
               <span>Escolher Imagem</span>
            </label>
            {{ form.imagem }}
            <img id="preview" src="#" alt="Pré-visualização" style="display: none; max-width: 100px;">
         </div>

         <!-- Botão de publicar -->
         <button type="submit" class="btn btn-primary">Publicar</button>
      </form>
   </div>
{% endblock %}

{% block script %}
   <script>
      document.getElementById('id_imagem').addEventListener('change', function(event) {
         const reader = new FileReader();
         reader.onload = function() {
            const preview = document.getElementById('preview');
            preview.src = reader.result;
            preview.style.display = 'block';
         };
         reader.readAsDataURL(event.target.files[0]);
      });
   </script>
{% endblock %}

blog_init/templates/novotopico.html
{% extends 'baseblog.html' %}
{% load static %}

{% block link %}
  <link rel="stylesheet" href="{% static 'perfil/css/adciTopicos.css' %}">
  <link rel="stylesheet" href="{% static 'perfil/css/cores.css' %}">
{% endblock %}
{% block main %}
  <div class="container">
    <div class="titulo">
      <p>Adicione um novo tópico</p>
    </div>
    
    <div class="Novo">
      <form action="{% url 'adicionarTopico' %}" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <div class="btn">
          <button name="submit">adicionar</button>
          <a href="{% url 'topicos'%}">Voltar</a>
        </div>
        </form>
    </div>
  </div>
{% endblock %}

blog_init/templates/perfil.html
{% extends 'baseblog.html' %}
{% load static %}

{% block link %}
   <link rel="stylesheet" href="{% static 'perfil/css/perfil.css'%}">
   <link rel="stylesheet" href="{% static 'perfil/css/cores.css'%}">
{% endblock %}

{% block main %}
  <div class="container">
     <h3>Olá, {{ user.username }}</h3>
     <p>Esse é seu perfil</p>
  </div>
  <div class="container2">
    <!-- Verifica se o usuário tem uma foto de perfil e exibe -->
    {% if user.perfil.foto %}
      <div class="img-foto">
        <img src="{{ user.perfil.foto.url }}" alt="Foto de perfil" id="profile-image">
      </div>
      <p class="Colocar">
        <a href="{% url 'uploadImage' %}" >Alterar foto</a>
     </p>
    {% else %}
      <p>Você ainda não tem uma foto de perfil.</p>
      <div class="img-foto"></div>
      <p class="Colocar"><a href="{% url 'uploadImage' %}">Colocar Foto</a></p>
    {% endif %}
    <h4>{{ user.username }}</h4>
  </div>
  <div class="container3">
    <p>Esse será o seu perfil onde todos poderão acessar e ver</p>
    <p>Em breve teremos mais funcionalidades.</p>
  </div>
{% endblock %}

blog_init/templates/perfilfoto.html
{% extends 'baseblog.html' %}
{% load static %}

{% block link %}
   <link rel="stylesheet" href="{% static 'perfil/css/perfilfoto.css'%}">
   <link rel="stylesheet" href="{% static 'perfil/css/cores.css'%}">
{% endblock %}

{% block main %}
<div class="foto">
   <form action="{% url 'uploadImage'%}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
       <!-- Campo de upload de imagem -->
       <div class="form-group">
        <label for="id_foto" class="custom-upload">
           <span>Escolher Imagem</span>
        </label>
        <input type="file" id="id_foto" name="foto" accept="image/*">
        <img id="preview" src="#" alt="Pré-visualização da imagem" style="display:none; max-width: 200px; max-height: 200px;">
     </div>
  
     <!-- Botão de enviar -->
     <button type="submit" class="btn btn-primary">Enviar</button>
     </form>
</div>
{% endblock %}

{% block script %}
<script>
   document.getElementById('id_foto').addEventListener('change', function(event) {
       const reader = new FileReader();
       reader.onload = function() {
           const preview = document.getElementById('preview');
           preview.src = reader.result;
           preview.style.display = 'block';
       };
       reader.readAsDataURL(event.target.files[0]);
   });
</script>
{% endblock %}

blog_init/templates/topicos.html
{% extends 'baseblog.html'%}
{% load static %}

{% block link%}
  <link rel="stylesheet" href="{% static 'perfil/css/topicos.css'%}">
  <link rel="stylesheet" href="{% static 'perfil/css/cores.css' %}">
{% endblock%}

{% block main %}
    <div class="container1">
      <h2>Tópicos</h2>
      <h4>A dicione seus tópicos aqui!</h4>
    </div>
    
    
    <a href="{% url 'adicionarTopico'%}" class="btn-adicionar">Novo Topico</a>

    <div class="topicos">
          {% if topicos %}
          <ul id="results">
            {% for topico in topicos %}
                <li>
                  {% if user.username|length > 50 %}
                   <p>{{ topico|slice:":50"}}</p>
                </li>
                  {% else %}
                  <p>{{ topico }}</p>
                  {% endif %}
                  <form method="post" action="{% url 'apagarTopico' topico.id %}" class="excluir">
                    {% csrf_token %}
                    <button type="submit">Excluir</button>
                  </form>
                </li>
            {% empty %}
                <li>Nenhum tópico encontrado.</li>
            {% endfor %}
        </ul>
    </div>
          {% else %}
          <p>Você ainda não tem tópicos.</p>
          {% endif %}
{% endblock %}

{% block script %}
  <script src="{% static 'perfil/js/script.js'%}"></script>
{% endblock %}

blog_init/templates/updatefoto.html
{% extends 'baseblog.html' %}
{% load static %}

{% block main %}
  
{% endblock %}